<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="10.1.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.12" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3" Version="4.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NymBroker.AzureServiceBus\NymBroker.AzureServiceBus.csproj" />
    <ProjectReference Include="..\NymBroker.Core\NymBroker.Core.csproj" />
    <ProjectReference Include="..\NymBroker.Idempotency.SqlServer\NymBroker.Idempotency.SqlServer.csproj" />
    <ProjectReference Include="..\NymBroker.Idempotency.Postgres\NymBroker.Idempotency.Postgres.csproj" />
    <ProjectReference Include="..\NymBroker.Idempotency.Sqlite\NymBroker.Idempotency.Sqlite.csproj" />
    <ProjectReference Include="..\NymBroker.Postgres\NymBroker.Postgres.csproj" />
    <ProjectReference Include="..\NymBroker.Sqlite\NymBroker.Sqlite.csproj" />
    <ProjectReference Include="..\NymBroker.SqlServer\NymBroker.SqlServer.csproj" />
  </ItemGroup>

</Project>